# Generated by Django 3.0.5 on 2020-05-05 00:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_auto_20200504_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Professor')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Endereço do Professor')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone do Professor')),
                ('email', models.CharField(max_length=255, verbose_name='Email do Professor')),
                ('salary', models.PositiveIntegerField(verbose_name='Salário do Professor')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
