# Generated by Django 3.0.5 on 2020-05-03 19:23

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Endereço do Aluno')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone do Aluno')),
                ('email', models.CharField(max_length=255, verbose_name='Email do Aluno')),
                ('art', models.CharField(max_length=255, verbose_name='Registro Acadêmico do Aluno')),
                ('course', models.CharField(choices=[('Eng. da Computação', 'Eng. da Computação'), ('Direito', 'Direito'), ('Pedagogia', 'Pedagogia')], default='Eng. da Computação', max_length=20, verbose_name='Curso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
